sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_7c1dff245ff0_key -iv $encrypted_7c1dff245ff0_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash  > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-220318
  - gcloud config set compute/zone northamerica-northeast1-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  - docker build -t thuriaux/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run thuriaux/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
